runTest: com/gregstoll/probabilityToFriendlyString/Tests.class
	java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore com.gregstoll.probabilityToFriendlyString.Tests

clean:
	rm com/gregstoll/probabilityToFriendlyString/*.class

com/gregstoll/probabilityToFriendlyString/Tests.class: com/gregstoll/probabilityToFriendlyString/Tests.java
	javac -cp .:/usr/share/java/junit4.jar com/gregstoll/probabilityToFriendlyString/Tests.java

