[package]
name = "probability_to_friendly_string"
version = "0.1.0"
authors = ["Greg Stoll <greg@gregstoll.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
